"""Derived engineering IR: the semantic graph behind a P&ID document.

Charter reference: §6 (semantic first), §8 (engineering objects, not pixels), §16
(M2 engineering semantic graph). The drawing document stores *geometry*; this module
derives the *engineering objects* an engineer actually reasons about:

    equipment · valve · instrument · line (pipeline) · junction · off_page_connector
    annotation · graphic

Design rules
------------
* **Derived, never authoritative.** The graph is a pure function of
  ``(document, symbol registry)``. Nothing here writes the document, so it cannot
  become a second source of truth. ``document_content_hash`` makes that function
  checkable, which is what lets the project index detect staleness.
* **Stable identity.** An object id is derived from its engineering tag
  (``valve:HV-101``) whenever the tag exists, so the same valve keeps the same
  identity across revisions even though its element id is regenerated by imports.
  Duplicate tags are disambiguated deterministically (``#2`` ordered by element id)
  and raise a finding instead of silently merging two real objects.
  ``identity_scope`` states honestly which basis was used: ``tag`` or ``element``.
* **Pixels never become engineering truth.** Coordinates, styles and SVG output are
  intentionally absent from the graph; geometry is only used for connectivity
  (ports, endpoints) and length.
* Signal/process classification is explicit-medium-driven, with one conservative
  structural rule (instrument-to-instrument). A process tap on a line is *not*
  reclassified as a signal.
"""

from __future__ import annotations

import hashlib
import json
from collections import Counter, defaultdict, deque
from math import hypot
from typing import Any, Literal

from pydantic import Field

from .flow_topology import is_opc_symbol, is_valve_symbol, normalize_flow_medium, opc_direction
from .models import Document, Element, StrictModel
from .symbols import SymbolRegistry

IR_SCHEMA = "pid-agent.engineering-graph"
IR_VERSION = 1
IR_BUILDER_VERSION = 1

ObjectKind = Literal[
    "equipment",
    "valve",
    "instrument",
    "line",
    "junction",
    "off_page_connector",
    "annotation",
    "graphic",
]
IdentityScope = Literal["tag", "element"]
FindingSeverity = Literal["info", "warning", "error"]
TraceDirection = Literal["upstream", "downstream", "both"]

#: Object kinds that participate in process topology (annotations/graphics do not).
TOPO_KINDS: frozenset[str] = frozenset(
    {"equipment", "valve", "instrument", "line", "junction", "off_page_connector"}
)

#: Mediums that mean "this connector carries an instrument signal, not process fluid".
_SIGNAL_TOKENS: tuple[str, ...] = (
    "signal",
    "signal_line",
    "electric",
    "electrical",
    "elec",
    "instrument",
    "instrumentation",
    "impulse",
    "pneumatic",
    "data",
    "communication",
    "信号",
    "电信号",
    "电气",
    "电",
    "气动",
    "脉冲",
    "通讯",
    "通信",
)


class EngineeringObject(StrictModel):
    """One engineering entity derived from one or more drawing elements."""

    object_id: str = Field(min_length=1)
    kind: ObjectKind
    identity_scope: IdentityScope
    tag: str = ""
    name: str = ""
    label: str = ""
    symbol_key: str = ""
    symbol_name: str = ""
    category: str = ""
    capability: str = ""
    element_ids: list[str] = Field(default_factory=list)
    primary_element_id: str
    layer_id: str = ""
    layer_name: str = ""
    system_id: str = ""
    system_name: str = ""
    media: str = ""
    medium_class: str = ""
    nominal_diameter: str = ""
    flow_direction: str = "none"
    required_port_count: int = 0
    connected_port_count: int = 0
    connection_count: int = 0
    length: float = 0.0
    opc_direction: Literal["in", "out", ""] = ""
    target_document_id: str = ""
    properties: dict[str, Any] = Field(default_factory=dict)


class TopologyEdge(StrictModel):
    """A directed (or undirected, when flow is undeclared) connection between objects."""

    connector_id: str
    pipeline_object_id: str
    source_object_id: str
    target_object_id: str
    source_port_id: str = ""
    target_port_id: str = ""
    medium: str = ""
    medium_class: str = ""
    flow_direction: Literal["forward", "reverse", "none"] = "none"
    directed: bool = False


class SignalLink(StrictModel):
    connector_id: str
    source_object_id: str = ""
    target_object_id: str = ""
    medium: str = ""
    instrument_object_ids: list[str] = Field(default_factory=list)
    classification: Literal["declared_medium", "instrument_to_instrument"] = "declared_medium"


class GraphFinding(StrictModel):
    severity: FindingSeverity
    code: str
    message: str
    object_ids: list[str] = Field(default_factory=list)
    element_ids: list[str] = Field(default_factory=list)
    details: dict[str, Any] = Field(default_factory=dict)


class EngineeringGraphCounts(StrictModel):
    equipment: int = 0
    valves: int = 0
    instruments: int = 0
    lines: int = 0
    junctions: int = 0
    off_page_connectors: int = 0
    annotations: int = 0
    graphics: int = 0
    objects: int = 0
    edges: int = 0
    signal_links: int = 0
    errors: int = 0
    warnings: int = 0
    info: int = 0


class EngineeringGraph(StrictModel):
    schema_name: Literal["pid-agent.engineering-graph"] = Field(
        default=IR_SCHEMA, alias="schema"
    )
    version: Literal[1] = IR_VERSION
    builder_version: Literal[1] = IR_BUILDER_VERSION
    document_id: str
    document_name: str
    revision: int
    content_hash: str
    counts: EngineeringGraphCounts
    objects: list[EngineeringObject]
    edges: list[TopologyEdge]
    signal_links: list[SignalLink]
    off_page_object_ids: list[str]
    connectivity_components: list[list[str]]
    findings: list[GraphFinding]

    def object(self, object_id: str) -> EngineeringObject | None:
        for item in self.objects:
            if item.object_id == object_id:
                return item
        return None


class TraceStep(StrictModel):
    depth: int
    object_id: str
    kind: ObjectKind
    via_connector_id: str = ""
    direction: Literal["upstream", "downstream", "undirected", "origin"] = "undirected"


class TraceResult(StrictModel):
    """Result of walking the graph.

    Steps are *engineering objects*. Pipelines are deliberately not steps: a pipeline
    aggregates every connector that shares a tag, so it is not a single node on a
    path. The pipelines actually traversed are reported separately, and a trace may
    also be *started* from a pipeline object to enumerate what it connects.
    """

    document_id: str
    revision: int
    origin_object_id: str
    direction: TraceDirection
    steps: list[TraceStep]
    reached_object_ids: list[str]
    traversed_pipeline_ids: list[str] = Field(default_factory=list)
    truncated: bool = False


# --------------------------------------------------------------------------- #
# Content hash
# --------------------------------------------------------------------------- #


def _element_projection(element: Element) -> dict[str, Any]:
    payload = element.model_dump(mode="json")
    payload["style"] = {}
    return payload


def document_content_hash(document: Document) -> str:
    """Hash the engineering content that the graph depends on.

    Editor-only fields (style, timestamps, name) are excluded so a restyle does not
    invalidate the index, while any change to identity, connectivity or attributes
    does. This is the staleness check for the project index.
    """

    payload = {
        "id": document.id,
        "layers": [layer.model_dump(mode="json") for layer in document.layers],
        "systems": [system.model_dump(mode="json") for system in document.systems],
        "elements": [
            _element_projection(element)
            for element in sorted(document.elements, key=lambda item: item.id)
        ],
    }
    canonical = json.dumps(payload, sort_keys=True, separators=(",", ":"), ensure_ascii=False)
    return hashlib.sha256(canonical.encode("utf-8")).hexdigest()


# --------------------------------------------------------------------------- #
# Identity helpers
# --------------------------------------------------------------------------- #


def _slug(value: str) -> str:
    cleaned = " ".join(value.strip().split()).casefold()
    out = [char if (char.isalnum() or char in "-_.") else "-" for char in cleaned]
    slug = "".join(out).strip("-")
    return slug or "unnamed"


_KIND_PREFIX: dict[str, str] = {
    "equipment": "equipment",
    "valve": "valve",
    "instrument": "instrument",
    "line": "line",
    "junction": "junction",
    "off_page_connector": "opc",
    "annotation": "annotation",
    "graphic": "graphic",
}


def _identity(
    kind: ObjectKind,
    tag: str,
    fallback: str,
    used: Counter[str],
) -> tuple[str, IdentityScope, str]:
    """Return (object_id, identity_scope, base_identity).

    The base identity is what an engineer would call the object (``valve:hv-101``).
    Collisions inside one document get a deterministic ``#n`` suffix ordered by
    element id, because two valves really can carry the same tag on a bad drawing and
    silently merging them would be an engineering lie.
    """

    if tag.strip():
        base = f"{_KIND_PREFIX[kind]}:{_slug(tag)}"
        scope: IdentityScope = "tag"
    else:
        base = f"{_KIND_PREFIX[kind]}:{fallback}"
        scope = "element"
    used[base] += 1
    if used[base] == 1:
        return base, scope, base
    return f"{base}#{used[base]}", scope, base


# --------------------------------------------------------------------------- #
# Element-level classification
# --------------------------------------------------------------------------- #


def _symbol_kind(element: Any, registry: SymbolRegistry) -> tuple[ObjectKind, str, str, Any]:
    """Return (kind, capability, definition_name, definition)."""

    try:
        definition = registry.get(element.symbol_key)
    except KeyError:
        return "equipment", "", "", None
    capability = str(definition.metadata.get("capability", "")).strip().casefold()
    if capability == "opc" or is_opc_symbol(element, registry):
        return "off_page_connector", "opc", definition.name, definition
    if capability == "valve" or is_valve_symbol(element, registry):
        return "valve", "valve", definition.name, definition
    if "仪表" in definition.category or "instrument" in definition.category.casefold():
        return "instrument", "instrument", definition.name, definition
    return "equipment", capability, definition.name, definition


def _port_connections(connectors: list[Any]) -> dict[tuple[str, str], set[str]]:
    connected: dict[tuple[str, str], set[str]] = defaultdict(set)
    for connector in connectors:
        for endpoint in (connector.source, connector.target):
            if endpoint and endpoint.element_id and endpoint.port_id:
                connected[(endpoint.element_id, endpoint.port_id)].add(connector.id)
    return connected


def _polyline_length(points: list[Any]) -> float:
    return sum(
        hypot(points[index + 1].x - points[index].x, points[index + 1].y - points[index].y)
        for index in range(len(points) - 1)
    )


def _classify_signal_medium(medium: str) -> bool:
    normalized = " ".join(medium.strip().casefold().replace("_", " ").split())
    if not normalized:
        return False
    return any(token in normalized for token in _SIGNAL_TOKENS)


# --------------------------------------------------------------------------- #
# Graph construction
# --------------------------------------------------------------------------- #


def build_engineering_graph(document: Document, registry: SymbolRegistry) -> EngineeringGraph:
    layer_names = {layer.id: layer.name for layer in document.layers}
    system_names = {system.id: system.name for system in document.systems}
    elements = list(document.elements)
    connectors = [element for element in elements if element.type == "connector"]
    connections = _port_connections(connectors)

    used: Counter[str] = Counter()
    objects: list[EngineeringObject] = []
    element_to_object: dict[str, str] = {}
    identity_duplicates: dict[str, list[str]] = defaultdict(list)
    findings: list[GraphFinding] = []

    def add_object(
        *,
        kind: ObjectKind,
        tag: str,
        fallback: str,
        element_ids: list[str],
        **fields: Any,
    ) -> EngineeringObject:
        object_id, scope, base = _identity(kind, tag, fallback, used)
        identity_duplicates[base].append(object_id)
        record = EngineeringObject(
            object_id=object_id,
            kind=kind,
            identity_scope=scope,
            tag=tag.strip(),
            element_ids=element_ids,
            primary_element_id=element_ids[0] if element_ids else fallback,
            **fields,
        )
        objects.append(record)
        return record

    # --- symbols ---------------------------------------------------------- #
    for element in elements:
        if element.type == "symbol":
            kind, capability, symbol_name, definition = _symbol_kind(element, registry)
            if definition is None:
                findings.append(
                    GraphFinding(
                        severity="error",
                        code="IR_SYMBOL_DEFINITION_MISSING",
                        message=f"符号 {element.id} 引用了未知图例 {element.symbol_key}。",
                        element_ids=[element.id],
                        details={"symbol_key": element.symbol_key},
                    )
                )
            required_ports = [
                port for port in (definition.ports if definition else []) if port.direction != "none"
            ]
            connected = sum(
                1 for port in required_ports if connections.get((element.id, port.id))
            )
            tag = element.label.strip() or str(element.properties.get("tag", "")).strip()
            record = add_object(
                kind=kind,
                tag=tag,
                fallback=element.id,
                element_ids=[element.id],
                name=element.name,
                label=element.label,
                symbol_key=element.symbol_key,
                symbol_name=symbol_name,
                category=definition.category if definition else "",
                capability=capability,
                layer_id=element.layer_id,
                layer_name=layer_names.get(element.layer_id, element.layer_id),
                system_id=element.system_id,
                system_name=system_names.get(element.system_id, element.system_id),
                required_port_count=len(required_ports),
                connected_port_count=connected,
                connection_count=sum(
                    len(connections.get((element.id, port.id), ())) for port in required_ports
                ),
                opc_direction=(
                    (opc_direction(element, registry) or "") if kind == "off_page_connector" else ""
                ),
                target_document_id=str(element.properties.get("target_document_id", "") or ""),
                properties=dict(element.properties),
            )
            element_to_object[element.id] = record.object_id
        elif element.type == "junction":
            record = add_object(
                kind="junction",
                tag=element.label.strip(),
                fallback=element.id,
                element_ids=[element.id],
                name=element.name,
                label=element.label,
                layer_id=element.layer_id,
                layer_name=layer_names.get(element.layer_id, element.layer_id),
                system_id=element.system_id,
                system_name=system_names.get(element.system_id, element.system_id),
                connection_count=sum(
                    1
                    for connector in connectors
                    if (connector.source and connector.source.element_id == element.id)
                    or (connector.target and connector.target.element_id == element.id)
                ),
            )
            element_to_object[element.id] = record.object_id
        elif element.type == "text":
            record = add_object(
                kind="annotation",
                tag="",
                fallback=element.id,
                element_ids=[element.id],
                name=element.name,
                label=element.text,
                layer_id=element.layer_id,
                layer_name=layer_names.get(element.layer_id, element.layer_id),
                system_id=element.system_id,
                system_name=system_names.get(element.system_id, element.system_id),
            )
            element_to_object[element.id] = record.object_id

    # --- pipelines (line aggregation) ------------------------------------- #
    pipelines: dict[tuple[str, ...], list[Any]] = defaultdict(list)
    for connector in connectors:
        tag = connector.process_tag.strip()
        if tag:
            key = (
                "tag",
                tag.casefold(),
                normalize_flow_medium(connector.medium),
                connector.nominal_diameter.strip().casefold(),
            )
        else:
            key = ("element", connector.id)
        pipelines[key].append(connector)

    for key in sorted(pipelines, key=lambda item: item):
        members = sorted(pipelines[key], key=lambda item: item.id)
        first = members[0]
        tag = first.process_tag.strip()
        media = sorted({member.medium.strip() for member in members if member.medium.strip()})
        diameters = sorted(
            {member.nominal_diameter.strip() for member in members if member.nominal_diameter.strip()}
        )
        endpoint_ids = sorted(
            {
                endpoint.element_id
                for member in members
                for endpoint in (member.source, member.target)
                if endpoint and endpoint.element_id
            }
        )
        record = add_object(
            kind="line",
            tag=tag,
            fallback=first.id,
            element_ids=[member.id for member in members],
            name=first.name,
            label=tag,
            media=" / ".join(media),
            medium_class=normalize_flow_medium(first.medium),
            nominal_diameter=" / ".join(diameters),
            flow_direction=first.flow_direction,
            connection_count=len(endpoint_ids),
            length=round(sum(_polyline_length(member.points) for member in members), 6),
            layer_id=first.layer_id,
            layer_name=layer_names.get(first.layer_id, first.layer_id),
            system_id=first.system_id,
            system_name=system_names.get(first.system_id, first.system_id),
            properties={"member_count": len(members)},
        )
        for member in members:
            element_to_object[member.id] = record.object_id

    # --- graphics (kept addressable, excluded from topology) -------------- #
    for element in elements:
        if element.type in {"line", "polyline", "rectangle", "circle"}:
            add_object(
                kind="graphic",
                tag="",
                fallback=element.id,
                element_ids=[element.id],
                name=element.name,
                layer_id=element.layer_id,
                layer_name=layer_names.get(element.layer_id, element.layer_id),
                system_id=element.system_id,
                system_name=system_names.get(element.system_id, element.system_id),
            )

    # --- topology edges ---------------------------------------------------- #
    edges: list[TopologyEdge] = []
    signal_links: list[SignalLink] = []
    for connector in sorted(connectors, key=lambda item: item.id):
        pipeline_id = element_to_object.get(connector.id, "")
        source_id = (
            element_to_object.get(connector.source.element_id, "")
            if connector.source and connector.source.element_id
            else ""
        )
        target_id = (
            element_to_object.get(connector.target.element_id, "")
            if connector.target and connector.target.element_id
            else ""
        )
        declared_direction = connector.flow_direction != "none"
        source_object = source_id or f"unbound:{connector.id}:source"
        target_object = target_id or f"unbound:{connector.id}:target"
        edge = TopologyEdge(
            connector_id=connector.id,
            pipeline_object_id=pipeline_id,
            source_object_id=source_object,
            target_object_id=target_object,
            source_port_id=(connector.source.port_id or "") if connector.source else "",
            target_port_id=(connector.target.port_id or "") if connector.target else "",
            medium=connector.medium,
            medium_class=normalize_flow_medium(connector.medium),
            flow_direction=connector.flow_direction,
            directed=declared_direction,
        )
        edges.append(edge)

        instrument_endpoints = sorted(
            object_id
            for object_id in (source_id, target_id)
            if object_id and _object_kind(objects, object_id) == "instrument"
        )
        declared_signal = _classify_signal_medium(connector.medium)
        structural_signal = len(instrument_endpoints) == 2
        if declared_signal or structural_signal:
            signal_links.append(
                SignalLink(
                    connector_id=connector.id,
                    source_object_id=source_id,
                    target_object_id=target_id,
                    medium=connector.medium,
                    instrument_object_ids=instrument_endpoints,
                    classification=(
                        "declared_medium" if declared_signal else "instrument_to_instrument"
                    ),
                )
            )

        if connector.source and connector.source.element_id and not source_id:
            findings.append(
                GraphFinding(
                    severity="error",
                    code="IR_ENDPOINT_ELEMENT_MISSING",
                    message=(
                        f"管线 {connector.process_tag.strip() or connector.id} 的 source 端引用了"
                        f"不存在的元素 {connector.source.element_id}。"
                    ),
                    element_ids=[connector.id, connector.source.element_id],
                    details={"endpoint": "source"},
                )
            )
        if connector.target and connector.target.element_id and not target_id:
            findings.append(
                GraphFinding(
                    severity="error",
                    code="IR_ENDPOINT_ELEMENT_MISSING",
                    message=(
                        f"管线 {connector.process_tag.strip() or connector.id} 的 target 端引用了"
                        f"不存在的元素 {connector.target.element_id}。"
                    ),
                    element_ids=[connector.id, connector.target.element_id],
                    details={"endpoint": "target"},
                )
            )

    # --- derived findings --------------------------------------------------- #
    for base, duplicates in sorted(identity_duplicates.items()):
        if len(duplicates) < 2:
            continue
        findings.append(
            GraphFinding(
                severity="error",
                code="IR_DUPLICATE_IDENTITY",
                message=f"工程标识 {base} 被 {len(duplicates)} 个对象重复使用。",                        object_ids=sorted(duplicates),
                        details={"identity": base, "count": len(duplicates)},
            )
        )

    for record in objects:
        if record.kind == "off_page_connector" and not record.target_document_id:
            findings.append(
                GraphFinding(
                    severity="warning",
                    code="IR_OPC_TARGET_MISSING",
                    message=f"跨图连接 {record.tag or record.object_id} 未声明目标图纸。",
                    object_ids=[record.object_id],
                    element_ids=list(record.element_ids),
                )
            )
        if record.kind in {"equipment", "valve"} and record.connection_count == 0:
            findings.append(
                GraphFinding(
                    severity="info",
                    code="IR_ISOLATED_OBJECT",
                    message=f"{record.label or record.object_id} 未与任何管线相连。",
                    object_ids=[record.object_id],
                    element_ids=list(record.element_ids),
                )
            )
        if record.kind == "line" and record.connection_count == 0:
            findings.append(
                GraphFinding(
                    severity="warning",
                    code="IR_ORPHAN_LINE",
                    message=f"管线 {record.tag or record.object_id} 两端均未绑定设备或连接节点。",
                    object_ids=[record.object_id],
                    element_ids=list(record.element_ids),
                )
            )

    for link in signal_links:
        if not link.instrument_object_ids:
            findings.append(
                GraphFinding(
                    severity="warning",
                    code="IR_SIGNAL_WITHOUT_INSTRUMENT",
                    message=f"信号连接 {link.connector_id} 未连接到任何仪表对象。",
                    element_ids=[link.connector_id],
                    details={"classification": link.classification},
                )
            )

    components = _connectivity_components(objects, edges)
    findings.sort(key=lambda item: (item.severity, item.code, tuple(item.object_ids), item.message))

    kind_count = Counter(record.kind for record in objects)
    return EngineeringGraph(
        document_id=document.id,
        document_name=document.name,
        revision=document.revision,
        content_hash=document_content_hash(document),
        counts=EngineeringGraphCounts(
            equipment=kind_count["equipment"],
            valves=kind_count["valve"],
            instruments=kind_count["instrument"],
            lines=kind_count["line"],
            junctions=kind_count["junction"],
            off_page_connectors=kind_count["off_page_connector"],
            annotations=kind_count["annotation"],
            graphics=kind_count["graphic"],
            objects=len(objects),
            edges=len(edges),
            signal_links=len(signal_links),
            errors=sum(item.severity == "error" for item in findings),
            warnings=sum(item.severity == "warning" for item in findings),
            info=sum(item.severity == "info" for item in findings),
        ),
        objects=objects,
        edges=edges,
        signal_links=signal_links,
        off_page_object_ids=sorted(
            record.object_id for record in objects if record.kind == "off_page_connector"
        ),
        connectivity_components=components,
        findings=findings,
    )


def _object_kind(objects: list[EngineeringObject], object_id: str) -> str:
    for record in objects:
        if record.object_id == object_id:
            return record.kind
    return ""


def _connectivity_components(
    objects: list[EngineeringObject],
    edges: list[TopologyEdge],
) -> list[list[str]]:
    """Union-find over process objects; annotations/graphics are excluded."""

    parent: dict[str, str] = {
        record.object_id: record.object_id for record in objects if record.kind in TOPO_KINDS
    }

    def find(node: str) -> str:
        root = node
        while parent[root] != root:
            root = parent[root]
        while parent[node] != root:
            parent[node], node = root, parent[node]
        return root

    def union(first: str, second: str) -> None:
        if first not in parent or second not in parent:
            return
        root_a, root_b = find(first), find(second)
        if root_a != root_b:
            parent[max(root_a, root_b)] = min(root_a, root_b)

    for edge in edges:
        union(edge.source_object_id, edge.target_object_id)
        if edge.pipeline_object_id:
            union(edge.source_object_id, edge.pipeline_object_id)
            union(edge.target_object_id, edge.pipeline_object_id)

    groups: dict[str, list[str]] = defaultdict(list)
    for node in parent:
        groups[find(node)].append(node)
    return sorted((sorted(members) for members in groups.values()), key=lambda item: item[0])


def graph_fingerprint(graph: EngineeringGraph) -> str:
    canonical = json.dumps(
        graph.model_dump(mode="json", by_alias=True),
        sort_keys=True,
        separators=(",", ":"),
        ensure_ascii=False,
    )
    return hashlib.sha256(canonical.encode("utf-8")).hexdigest()


# --------------------------------------------------------------------------- #
# Tracing
# --------------------------------------------------------------------------- #


def _neighbours(
    edges: list[TopologyEdge],
    node: str,
) -> list[tuple[str, str, Literal["upstream", "downstream", "undirected"]]]:
    """Return (neighbour, connector_id, direction) sorted for determinism."""

    out: list[tuple[str, str, Literal["upstream", "downstream", "undirected"]]] = []
    for edge in edges:
        if edge.source_object_id == node and edge.target_object_id:
            out.append(
                (
                    edge.target_object_id,
                    edge.connector_id,
                    "downstream" if edge.directed else "undirected",
                )
            )
        if edge.target_object_id == node and edge.source_object_id:
            out.append(
                (
                    edge.source_object_id,
                    edge.connector_id,
                    "upstream" if edge.directed else "undirected",
                )
            )
    return sorted(out, key=lambda item: (item[0], item[1]))


def _node_neighbours(
    graph: EngineeringGraph,
    node: str,
) -> list[tuple[str, str, Literal["upstream", "downstream", "undirected"]]]:
    """Expand one node, including the "start from a pipeline" case.

    For a pipeline node the members are the connectors sharing that tag: their
    endpoints are reported with the pipeline's own reading direction (declared
    source is upstream, declared target is downstream; undeclared flow is
    undirected), which is the only interpretation the drawing actually supports.
    """

    member_edges = [edge for edge in graph.edges if edge.pipeline_object_id == node]
    if not member_edges:
        return _neighbours(graph.edges, node)
    out: list[tuple[str, str, Literal["upstream", "downstream", "undirected"]]] = []
    for edge in member_edges:
        for endpoint_id, edge_direction in (
            (edge.source_object_id, "upstream"),
            (edge.target_object_id, "downstream"),
        ):
            if not endpoint_id or endpoint_id.startswith("unbound:"):
                continue
            out.append(
                (endpoint_id, edge.connector_id, edge_direction if edge.directed else "undirected")
            )
    return sorted(out, key=lambda item: (item[0], item[1]))


def trace_engineering_object(
    graph: EngineeringGraph,
    object_id: str,
    *,
    direction: TraceDirection = "both",
    max_depth: int = 64,
    max_steps: int = 512,
) -> TraceResult:
    """Walk the graph from one engineering object.

    Direction is honoured only for edges that declare a flow direction; undeclared
    (``none``) connections are traversable both ways, which matches how a P&ID is
    actually read (topology first, flow second).
    """

    if graph.object(object_id) is None:
        raise KeyError(f"unknown engineering object: {object_id}")
    allowed: set[str]
    if direction == "both":
        allowed = {"upstream", "downstream", "undirected"}
    elif direction == "downstream":
        allowed = {"downstream", "undirected"}
    else:
        allowed = {"upstream", "undirected"}

    steps: list[TraceStep] = [
        TraceStep(
            depth=0,
            object_id=object_id,
            kind=graph.object(object_id).kind,  # type: ignore[union-attr]
            direction="origin",
        )
    ]
    visited = {object_id}
    queue: deque[tuple[str, int]] = deque([(object_id, 0)])
    truncated = False
    while queue:
        node, depth = queue.popleft()
        if depth >= max_depth:
            truncated = True
            continue
        for neighbour, connector_id, edge_direction in _node_neighbours(graph, node):
            if edge_direction not in allowed:
                continue
            if neighbour in visited or neighbour.startswith("unbound:"):
                continue
            if len(steps) >= max_steps:
                truncated = True
                break
            visited.add(neighbour)
            record = graph.object(neighbour)
            steps.append(
                TraceStep(
                    depth=depth + 1,
                    object_id=neighbour,
                    kind=record.kind if record else "graphic",
                    via_connector_id=connector_id,
                    direction=edge_direction,
                )
            )
            queue.append((neighbour, depth + 1))
    traversed = {
        edge.pipeline_object_id
        for edge in graph.edges
        if edge.connector_id in {step.via_connector_id for step in steps if step.via_connector_id}
        and edge.pipeline_object_id
    }
    return TraceResult(
        document_id=graph.document_id,
        revision=graph.revision,
        origin_object_id=object_id,
        direction=direction,
        steps=steps,
        reached_object_ids=sorted(visited),
        traversed_pipeline_ids=sorted(traversed),
        truncated=truncated,
    )


__all__ = [
    "IR_BUILDER_VERSION",
    "IR_SCHEMA",
    "IR_VERSION",
    "TOPO_KINDS",
    "EngineeringGraph",
    "EngineeringGraphCounts",
    "EngineeringObject",
    "GraphFinding",
    "SignalLink",
    "TopologyEdge",
    "TraceResult",
    "TraceStep",
    "build_engineering_graph",
    "document_content_hash",
    "graph_fingerprint",
    "trace_engineering_object",
]
